spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=false

jwt.secret=${JWT_SECRET:minha-chave-local-apenas-desenvolvimento}

app.cors.allowed-origins=http://localhost:3000